"""Create category table and link to activities

Revision ID: 47dd714c58f7
Revises: 990eabe602fb
Create Date: 2025-09-05 11:22:27.825344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # <--- THIS IS THE CRITICAL FIX


# revision identifiers, used by Alembic.
revision: str = '47dd714c58f7'
down_revision: Union[str, Sequence[str], None] = '990eabe602fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_user_id'), 'category', ['user_id'], unique=False)
    op.add_column('loggedactivity', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loggedactivity', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loggedactivity', type_='foreignkey')
    op.drop_column('loggedactivity', 'category_id')
    op.drop_index(op.f('ix_category_user_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###