"""Add color column to category table

Revision ID: 7f4b7c12bdae
Revises: cf54bb931fea
Create Date: 2025-10-10 23:50:40.867569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add this line


# revision identifiers, used by Alembic.
revision: str = '7f4b7c12bdae'
down_revision: Union[str, Sequence[str], None] = 'cf54bb931fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if the column already exists before adding it
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('category')]
    
    if 'color' not in columns:
        # 1. Add the column as nullable first
        op.add_column('category', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        
        # 2. Update existing rows with a default value
        op.execute("UPDATE category SET color = '#FFFFFF' WHERE color IS NULL")
        
        # 3. Alter the column to nullable=False
        op.alter_column('category', 'color', nullable=False, existing_type=sqlmodel.sql.sqltypes.AutoString())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'color')
    # ### end Alembic commands ###
