"""Add category column to logged_activity table

Revision ID: 990eabe602fb
Revises: 
Create Date: 2025-08-29 07:26:06.698672

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '990eabe602fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('loggedactivity', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # op.create_index(op.f('ix_loggedactivity_category'), 'loggedactivity', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loggedactivity_category'), table_name='loggedactivity')
    op.drop_column('loggedactivity', 'category')
    # ### end Alembic commands ###
