"""Refactor Category model and add DailyTarget table

Revision ID: cf54bb931fea
Revises: 47dd714c58f7
Create Date: 2025-10-10 18:46:06.482150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf54bb931fea'
down_revision: Union[str, Sequence[str], None] = '47dd714c58f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailytarget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_hours', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dailytarget_user_id'), 'dailytarget', ['user_id'], unique=False)
    op.drop_index(op.f('early_signups_email_unique_ci'), table_name='early_signups')
    op.drop_table('early_signups')
    op.drop_index(op.f('ix_daily_targets_user_id'), table_name='daily_targets')
    op.drop_table('daily_targets')
    op.create_unique_constraint('unique_user_category_name', 'category', ['user_id', 'name'])
    op.drop_column('category', 'color')
    op.drop_column('category', 'is_default')
    op.alter_column('goal', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('goal', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('loggedactivity', 'activity_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_loggedactivity_category'), table_name='loggedactivity')
    op.drop_constraint(op.f('loggedactivity_category_id_fkey'), 'loggedactivity', type_='foreignkey')
    op.drop_column('loggedactivity', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loggedactivity', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('loggedactivity_category_id_fkey'), 'loggedactivity', 'category', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_loggedactivity_category'), 'loggedactivity', ['category'], unique=False)
    op.alter_column('loggedactivity', 'activity_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('goal', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('goal', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('category', sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('category', sa.Column('color', sa.VARCHAR(length=7), autoincrement=False, nullable=False))
    op.drop_constraint('unique_user_category_name', 'category', type_='unique')
    op.create_table('daily_targets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_targets_pkey'))
    )
    op.create_index(op.f('ix_daily_targets_user_id'), 'daily_targets', ['user_id'], unique=False)
    op.create_table('early_signups',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('early_signups_pkey'))
    )
    op.create_index(op.f('early_signups_email_unique_ci'), 'early_signups', [sa.literal_column('lower(email)')], unique=True)
    op.drop_index(op.f('ix_dailytarget_user_id'), table_name='dailytarget')
    op.drop_table('dailytarget')
    # ### end Alembic commands ###
